#!/usr/bin/env bash

set -eux

rm -rf www
mkdir -p www

cd www
git clone https://github.com/ocaml/opam-repository --depth 1

cp -r ../content .
mkdir -p content/doc/{1.1,1.2,2.0}
git clone https://github.com/ocaml/opam.wiki.git --depth 1 -b old_wiki content/doc/1.1
cp -r ../../opam/doc/pages/* content/doc
cp -r ../../opam/doc/html content/doc/2.0/api
cp -r ../../opam/doc/man-html content/doc/2.0/man

../_build/default/bin/opam2web.exe --content content . -r 'http://127.0.0.1:8080'
cp -r -L ../ext .
micro_httpd # &
# xdg-open 'http://127.0.0.1:8080/index.html'
# trap 'kill %%' EXIT
# wait %%
