open Cow
open Cow.Html

let string_of_time () =
  let t = Unix.localtime (Unix.time ()) in
  Printf.sprintf "%d/%d/%d" t.Unix.tm_mday (t.Unix.tm_mon + 1) (t.Unix.tm_year + 1900)

let create ~title ~header ~body ~footer =
  <:xml<
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>OPAM - $str: title$</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="The homepage of OPAM, a package manager for OCaml" />
    <meta name="author" content="OCamlPro" />

    <!-- Le styles -->
    <link href="css/bootstrap.css" rel="stylesheet" />
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="js/google-code-prettify/prettify.css" rel="stylesheet" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"> </span>
            <span class="icon-bar"> </span>
            <span class="icon-bar"> </span>
          </a>
          <a class="brand" href="#">OPAM</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="packages.html">Packages</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation <b class="caret"> </b></a>
                <ul class="dropdown-menu">
                  <li><a href="doc/tutorial.html">Tutorial</a></li>
                  <li><a href="doc/tutorial_packager.html">Packager tutorial</a></li>
                  <li><a href="doc/tutorial_developer.html">Developer tutorial</a></li>
                  <li class="divider"> </li>
                  <li class="nav-header">User manual</li>
                  <li><a href="#">Install OPAM</a></li>
                  <li><a href="#">Install packages</a></li>
                  <li class="nav-header">Packager manual</li>
                  <li><a href="#">Create a package</a></li>
                  <li><a href="#">Publish a package</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Search packages" />
              <!-- <button type="submit" class="btn">Search</button> -->
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      $body$

      <hr />

      <footer>
        $footer$
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"> </script>
    <script src="js/google-code-prettify/prettify.js"> </script>
    <script src="js/bootstrap.min.js"> </script>
    <script src="js/site.js"> </script>

  </body>
</html>
  >>

let make_nav current pages =
  let one (l,_) =
    if l = current then
      <:xml< <div id="current">$html_of_link l$</div> >>
    else
      html_of_link l in
    let inter = <:xml< <li>::</li> >> in
    let rec aux = function
      | []   -> []
      | [h]  -> [one h]
      | h::t -> (one h) :: inter :: aux t in
    <:xml<
      <div class="nav"><ul>$list:aux pages$</ul></div>
    >>

let process ~out_dir pages =
  let footer = <:xml<
      <p>
        Last modified: $str:string_of_time ()$ –
        Generated by <a href="https://github.com/mirage/ocaml-cow" title="OCaml on the Web">COW</a>.<br />
        © <a href="http://www.ocamlpro.com/">OCamlPro</a> 2012
      </p>
    >> in
  let aux (link, contents) =
    Printf.printf "> %s... %!" link.href;
    let header = make_nav link pages in
    let chan = open_out (out_dir ^ link.href) in
    let page = create ~title:link.text ~header ~body:contents ~footer in
    output_string chan (Html.to_string page);
    close_out chan;
    Printf.printf "[Done]\n"
  in
  List.iter aux pages

let generate ~out_dir pages =
  Printf.printf "Generating html files:\n%!";
  process ~out_dir pages;

